#! /bin/bash
### BEGIN INIT INFO
# Provides:          sprinkler
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Sets water sensor state for irrigation system
# Description:       Sets water sensor state for irrigation system
### END INIT INFO

DESC="Sets water sensor state for irrigation system"
NAME='sprinkler'
DAEMON="/bin/node"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
APPDIR=/opt/sprinkler

GPIO_BIN='/usr/bin/raspi-gpio'
GPIO_ARGS="set 23"

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME
DAEMON_ARGS="$APPDIR/sprinkler.js $LATITUDE $LONGITUDE"

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

#
# Function that starts the daemon/service
#
do_start()
{
  # Reset GPIO pin
  $GPIO_BIN $GPIO_ARGS op
  $GPIO_BIN $GPIO_ARGS dl
  $GPIO_BIN $GPIO_ARGS dh

  $DAEMON $DAEMON_ARGS 2>&1 | /usr/bin/logger -t SPRINKLER
}

#
# Function that stops the daemon/service
#
do_stop()
{
  # Reset GPIO pin
  $GPIO_BIN $GPIO_ARGS op
  $GPIO_BIN $GPIO_ARGS dl
  $GPIO_BIN $GPIO_ARGS dh
}

#
# Function that sends a SIGHUP to the daemon/service
#
do_reload()
{
  start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
  return 0
}

case "$1" in
  start)
  [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
  do_start
  case "$?" in
    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
    2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
  esac
  ;;
  stop)
  [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
  do_stop
  case "$?" in
    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
    2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
  esac
  ;;
  status)
  status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
  ;;
  restart|force-reload)
  log_daemon_msg "Restarting $DESC" "$NAME"
  do_stop
  case "$?" in
    0|1)
    do_start
    case "$?" in
      0) log_end_msg 0 ;;
      1) log_end_msg 1 ;; # Old process is still running
      *) log_end_msg 1 ;; # Failed to start
    esac
    ;;
    *)
    # Failed to stop
    log_end_msg 1
    ;;
  esac
  ;;
  *)
  echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
  exit 3
  ;;
esac

:
