name: Automated Testing

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    branches: [ main ]

jobs:
  unittest:
    if: '! github.event.pull_request.draft'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
        cache: npm
    - run: npm ci
    - name: Run JavaScript Unit Tests
      run: npm test
