name: Package the Distribution

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Create Release Package
        uses: actions/upload-artifact@v4
        with:
          name: SprinklerSwitch.v${{ github.ref_name }}
          path: |
            src/
            etc/
            install.sh
            package*.json
            README.md
            LICENSE
